//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAptitudeExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDetail
    {
        public int id { get; set; }
        public int exam_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string selected_question { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
    }
}
